# Generated by Django 6.0.1 on 2026-01-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.PositiveIntegerField(unique=True)),
                ('Visitor_name', models.CharField(max_length=100)),
                ('Visitor_email', models.EmailField(max_length=254)),
                ('Category', models.CharField(max_length=50)),
                ('Document', models.FileField(upload_to='visitors document')),
                ('Appointment_Date', models.DateField()),
                ('Appointment_Time', models.TimeField()),
                ('reason', models.TextField()),
                ('designated_attendee', models.CharField(max_length=100)),
                ('document', models.FileField(blank=True, null=True, upload_to='visitor_documents/')),
            ],
        ),
    ]
