# Generated by Django 6.0.1 on 2026-01-21 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='visitors',
            new_name='Visitor',
        ),
        migrations.CreateModel(
            name='VisitorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Reschedule', 'Reschedule')], default='Pending', max_length=50)),
                ('rescheduled_date', models.DateField(blank=True, null=True)),
                ('rescheduled_time', models.TimeField(blank=True, null=True)),
                ('designated_attendee', models.CharField(blank=True, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=4, null=True)),
                ('in_time', models.TimeField(blank=True, null=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('total_duration', models.DurationField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('visitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.visitor')),
            ],
        ),
    ]
