# Generated by Django 6.0.1 on 2026-01-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_visitors_visitor_visitorschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='Appointment_Date',
            new_name='appointment_date',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='Appointment_Time',
            new_name='appointment_time',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='Visitor_email',
            new_name='visitor_email',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='Visitor_name',
            new_name='visitor_name',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='Document',
        ),
        migrations.AlterField(
            model_name='visitorschedule',
            name='designated_attendee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitorschedule',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Rescheduled', 'Rescheduled')], default='Pending', max_length=50),
        ),
    ]
