# Generated by Django 5.2.4 on 2026-02-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_visitor_id_alter_visitorschedule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
