# Generated by Django 6.0.1 on 2026-02-04 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_visitor_id_alter_visitorschedule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='visitorschedule',
            name='visitor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='myapp.visitor'),
        ),
    ]
