# Generated by Django 6.0.1 on 2026-02-04 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_visitor_status_alter_visitor_visitor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='rescheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='rescheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='total_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='verification_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Rescheduled', 'Rescheduled')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitorschedule',
            name='visitor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.visitor'),
        ),
    ]
